table Date
	lineageTag: 4e1127c7-2dcf-436c-b9bd-f8ea079d7a44

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f807f5f1-654d-405e-8580-a00fae7231e1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a1099cd7-2b4f-4507-b0e5-88ea76cc854a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month_Num
		dataType: int64
		formatString: 0
		lineageTag: baa47569-aa17-48a1-baa6-56725891242e
		summarizeBy: sum
		sourceColumn: Month_Num

		annotation SummarizationSetBy = Automatic

	column Month_Short
		dataType: string
		lineageTag: eef62ae5-bfbe-4dd8-b5da-74fb15d9bbda
		summarizeBy: none
		sourceColumn: Month_Short

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 84efeccd-6f12-4f23-995a-0fc373d7e72d
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 7961c09e-b66c-4fec-b94c-d1c6cffcedf7
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: int64
		formatString: 0
		lineageTag: de4f38ca-48f8-4c4c-82fa-f393ccdf28c3
		summarizeBy: sum
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	column Day_of_Week
		dataType: string
		lineageTag: 0a33bcd6-bbc9-48a1-8923-f53fe207b835
		summarizeBy: none
		sourceColumn: Day_of_Week

		annotation SummarizationSetBy = Automatic

	column Month_Year
		dataType: dateTime
		formatString: Long Date
		lineageTag: daa7af8c-ad1b-41ea-a717-23da938ca609
		summarizeBy: none
		sourceColumn: Month_Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year_Month
		dataType: string
		lineageTag: 6c02610b-099a-45fa-87de-34a0a814c4e9
		summarizeBy: none
		sourceColumn: Year_Month

		annotation SummarizationSetBy = Automatic

	column Timeframe = IF('Date'[Date] >= FIRSTDATE(people_fact[hire_date]) && 'Date'[Date]<= TODAY(),1,0)
		formatString: 0
		lineageTag: 09d55aa1-3d43-420d-9f0a-9e7abab56038
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		queryGroup: 'source tables'
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Taarika\BA-BI-Documents (Taarika)\Projects - BI\HR People Analysis\data\Dates.xlsx"), null, true),
				    #"Dates (Big)_Sheet" = Source{[Item="Dates (Big)",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Dates (Big)_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Year", Int64.Type}, {"Month_Num", Int64.Type}, {"Month_Short", type text}, {"Month", type text}, {"Day", Int64.Type}, {"Weekday", Int64.Type}, {"Day_of_Week", type text}, {"Month_Year", type date}, {"Year_Month", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

