table job_level_dim
	lineageTag: 162d273d-e6d4-49c7-8fd6-6ea61c7da10c

	column job_level
		dataType: string
		lineageTag: e73110e6-ce23-4a5e-aa6c-a4a738b70109
		summarizeBy: none
		sourceColumn: job_level

		annotation SummarizationSetBy = Automatic

	column job_level_key
		dataType: int64
		formatString: 0
		lineageTag: 8eef534a-01f6-4feb-97a0-9a814de307a8
		summarizeBy: none
		sourceColumn: job_level_key

		annotation SummarizationSetBy = Automatic

	partition job_level_dim = m
		mode: import
		queryGroup: 'production tables'
		source =
				let
				    Source = people_employment_source,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"job_level"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "job_level_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

