table location_dim
	lineageTag: 3734c0e5-be45-4aeb-9042-5674cbfc0461

	column location
		dataType: string
		lineageTag: 4c738005-1dd5-4345-92b1-19db46eb2a1f
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column location_city
		dataType: string
		lineageTag: 9d387cf3-c2af-41a5-a08a-0a0d31cef68c
		summarizeBy: none
		sourceColumn: location_city

		annotation SummarizationSetBy = Automatic

	column location_key
		dataType: int64
		formatString: 0
		lineageTag: 323ca2bc-0bd4-4a2a-b082-6d3c96e2199e
		summarizeBy: none
		sourceColumn: location_key

		annotation SummarizationSetBy = Automatic

	partition location_dim = m
		mode: import
		queryGroup: 'production tables'
		source =
				let
				    Source = people_data_source,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"location", "location_city"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "location_key"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

