table people_fact
	lineageTag: 903bd698-74bb-4494-9c61-919a29657f75

	column employee_id
		dataType: string
		lineageTag: 90bc71c9-eaf9-49d8-b72f-d47a891b02e3
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 738051ca-fb6a-434a-b01a-94c80299e3b5
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: fc4c12c3-3175-4ab0-a9dc-ca2dc2617570
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column salary
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: a6d513bb-a35e-41b6-802c-b233269d8b03
		summarizeBy: sum
		sourceColumn: salary

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column hire_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2942174d-3cd9-47e4-b38a-34922c9f3f3a
		summarizeBy: none
		sourceColumn: hire_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column term_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: effa9ced-3302-48a7-b29f-da49573de695
		summarizeBy: none
		sourceColumn: term_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column active_status
		dataType: string
		lineageTag: d7093839-989c-44c4-a98e-cb3b8179a075
		summarizeBy: none
		sourceColumn: active_status

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 2bf96bca-4e19-48e9-b478-6469182c2b0a
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column department_key
		dataType: int64
		formatString: 0
		lineageTag: 6d093f85-12e7-4b08-b48b-dc8295de5981
		summarizeBy: none
		sourceColumn: department_key

		annotation SummarizationSetBy = Automatic

	column job_level_key
		dataType: int64
		formatString: 0
		lineageTag: 561c7e4f-d04d-4658-90cf-85154cde9c32
		summarizeBy: none
		sourceColumn: job_level_key

		annotation SummarizationSetBy = Automatic

	column term_key
		dataType: int64
		formatString: 0
		lineageTag: 2f65eb05-46ea-4544-9a01-7199f53fba6c
		summarizeBy: none
		sourceColumn: term_key

		annotation SummarizationSetBy = Automatic

	column demog_key
		dataType: int64
		formatString: 0
		lineageTag: 2a109ce9-fa2c-404f-b411-9a058b1ae84d
		summarizeBy: none
		sourceColumn: demog_key

		annotation SummarizationSetBy = Automatic

	column education_key
		dataType: int64
		formatString: 0
		lineageTag: ab6ad663-b7aa-4eeb-b2ac-e810f8136e3d
		summarizeBy: none
		sourceColumn: education_key

		annotation SummarizationSetBy = Automatic

	column location_key
		dataType: int64
		formatString: 0
		lineageTag: b350a178-3b89-4801-b2e8-bd668acc0db1
		summarizeBy: none
		sourceColumn: location_key

		annotation SummarizationSetBy = Automatic

	column marital_key
		dataType: int64
		formatString: 0
		lineageTag: 644eba6b-5aff-4300-b218-ae624f530609
		summarizeBy: none
		sourceColumn: marital_key

		annotation SummarizationSetBy = Automatic

	column full_name
		dataType: string
		lineageTag: 92f06e7f-448a-4715-a0d2-663b90201ebc
		summarizeBy: none
		sourceColumn: full_name

		annotation SummarizationSetBy = Automatic

	partition people_fact = m
		mode: import
		queryGroup: 'production tables'
		source =
				let
				    Source = people_employment_source,
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"active_status", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","1","Yes",Replacer.ReplaceText,{"active_status"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","0","No",Replacer.ReplaceText,{"active_status"}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value1", {"department", "sub-department"}, department_dim, {"department", "sub-department"}, "department_dim", JoinKind.LeftOuter),
				    #"Expanded department_dim" = Table.ExpandTableColumn(#"Merged Queries", "department_dim", {"department_key"}, {"department_dim.department_key"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded department_dim",{{"department_dim.department_key", "department_key"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"employee_id", "first_name", "last_name", "first_level_manager", "second_level_manager", "third_level_manager", "fourth_level_manager", "job_level", "salary", "hire_date", "term_date", "term_type", "term_reason", "active_status", "department_key"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Other Columns", {"job_level"}, job_level_dim, {"job_level"}, "job_level_dim", JoinKind.LeftOuter),
				    #"Expanded job_level_dim" = Table.ExpandTableColumn(#"Merged Queries1", "job_level_dim", {"job_level_key"}, {"job_level_key"}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Expanded job_level_dim", "full_name", each Text.Combine({[first_name], [last_name]}, " "), type text),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Inserted Merged Column",{"employee_id", "first_name", "last_name", "full_name", "first_level_manager", "second_level_manager", "third_level_manager", "fourth_level_manager", "job_level", "salary", "hire_date", "term_date", "term_type", "term_reason", "active_status", "department_key", "job_level_key"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Reordered Columns1",{"employee_id", "first_name", "last_name", "first_level_manager", "second_level_manager", "third_level_manager", "fourth_level_manager", "salary", "hire_date", "term_date", "term_type", "term_reason", "active_status", "department_key", "job_level_key"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Removed Other Columns1", {"term_type", "term_reason"}, term_dim, {"term_type", "term_reason"}, "term_dim", JoinKind.LeftOuter),
				    #"Expanded term_dim" = Table.ExpandTableColumn(#"Merged Queries2", "term_dim", {"term_key"}, {"term_key"}),
				    #"Removed Other Columns2" = Table.SelectColumns(#"Expanded term_dim",{"employee_id", "first_name", "last_name", "first_level_manager", "second_level_manager", "third_level_manager", "fourth_level_manager", "salary", "hire_date", "term_date", "active_status", "department_key", "job_level_key", "term_key"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Other Columns2",{{"employee_id", type text}, {"first_level_manager", type text}, {"second_level_manager", type text}, {"third_level_manager", type text}, {"fourth_level_manager", type text}}),
				    #"Removed Other Columns3" = Table.SelectColumns(#"Changed Type1",{"employee_id", "first_name", "last_name", "salary", "hire_date", "term_date", "active_status", "department_key", "job_level_key", "term_key"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Other Columns3",{{"salary", Currency.Type}}),
				    #"Merged Queries3" = Table.NestedJoin(#"Changed Type2", {"employee_id"}, people_data_source, {"employee_id"}, "people_data_source", JoinKind.LeftOuter),
				    #"Expanded people_data_source" = Table.ExpandTableColumn(#"Merged Queries3", "people_data_source", {"gender", "race", "age", "education", "location", "location_city", "marital_status", "employment_status"}, {"gender", "race", "age", "education", "location", "location_city", "marital_status", "employment_status"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Expanded people_data_source", {"gender", "race", "age"}, demographic_dim, {"gender", "race", "age"}, "demographic_dim", JoinKind.LeftOuter),
				    #"Expanded demographic_dim" = Table.ExpandTableColumn(#"Merged Queries4", "demographic_dim", {"demog_key"}, {"demog_key"}),
				    #"Removed Other Columns4" = Table.SelectColumns(#"Expanded demographic_dim",{"employee_id", "first_name", "last_name", "salary", "hire_date", "term_date", "active_status", "department_key", "job_level_key", "term_key", "education", "location", "location_city", "marital_status", "employment_status", "demog_key"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns4",{"employee_id", "first_name", "last_name", "salary", "hire_date", "term_date", "active_status", "employment_status", "department_key", "job_level_key", "term_key", "education", "location", "location_city", "marital_status", "demog_key"}),
				    #"Merged Queries5" = Table.NestedJoin(#"Reordered Columns", {"education"}, education_dim, {"education"}, "education_dim", JoinKind.LeftOuter),
				    #"Expanded education_dim" = Table.ExpandTableColumn(#"Merged Queries5", "education_dim", {"education_key"}, {"education_key"}),
				    #"Removed Other Columns5" = Table.SelectColumns(#"Expanded education_dim",{"employee_id", "first_name", "last_name", "salary", "hire_date", "term_date", "active_status", "employment_status", "department_key", "job_level_key", "term_key", "location", "location_city", "marital_status", "demog_key", "education_key"}),
				    #"Merged Queries6" = Table.NestedJoin(#"Removed Other Columns5", {"location", "location_city"}, location_dim, {"location", "location_city"}, "location_dim", JoinKind.LeftOuter),
				    #"Expanded location_dim" = Table.ExpandTableColumn(#"Merged Queries6", "location_dim", {"location_key"}, {"location_key"}),
				    #"Removed Other Columns6" = Table.SelectColumns(#"Expanded location_dim",{"employee_id", "first_name", "last_name", "salary", "hire_date", "term_date", "active_status", "employment_status", "department_key", "job_level_key", "term_key", "marital_status", "demog_key", "education_key", "location_key"}),
				    #"Merged Queries7" = Table.NestedJoin(#"Removed Other Columns6", {"marital_status"}, marital_dim, {"marital_status"}, "marital_dim", JoinKind.LeftOuter),
				    #"Expanded marital_dim" = Table.ExpandTableColumn(#"Merged Queries7", "marital_dim", {"marital_key"}, {"marital_key"}),
				    #"Removed Other Columns7" = Table.SelectColumns(#"Expanded marital_dim",{"employee_id", "first_name", "last_name", "salary", "hire_date", "term_date", "active_status", "employment_status", "department_key", "job_level_key", "term_key", "demog_key", "education_key", "location_key", "marital_key"}),
				    #"Inserted Merged Column1" = Table.AddColumn(#"Removed Other Columns7", "full_name", each Text.Combine({[first_name], [last_name]}, " "), type text),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Inserted Merged Column1",{"employee_id", "first_name", "last_name", "full_name", "salary", "hire_date", "term_date", "active_status", "employment_status", "department_key", "job_level_key", "term_key", "demog_key", "education_key", "location_key", "marital_key"})
				in
				    #"Reordered Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

